=== voltumna-linux/meta-voltumna/openembedded-core/meta/files/bitbake-setup.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "description": "Schema for bitbake-setup configuration files",
    "type": "object",
    "required": [
        "description",
        "bitbake-setup",
        "version"
    ],
    "properties": {
        "description": {
            "type": "string",
            "description": "Description of the bitbake-setup configuration file"
        },
        "sources": {
            "$ref": "layers.schema.json#/properties/sources"
        },
        "bitbake-setup": {
            "type": "object",
            "description": "BitBake-setup configurations",
            "required": [
                "configurations"
            ],
            "properties": {
                "configurations": {
                    "type": "array",
                    "minItems": 1,
                    "$anchor": "configurations",
                    "items": {
                        "type": "object",
                        "properties": {
                            "name": {
                                "type": "string",
                                "description": "Name of the configuration"
                            },
                            "description": {
                                "type": "string",
                                "description": "Human-readable description of the configuration"
                            },
                            "bb-layers": {
                                "type": "array",
                                "description": "List of BitBake layers to include",
                                "items": {
                                    "type": "string"
                                }
                            },
                            "oe-template": {
                                "type": "string",
                                "description": "OE-template configuration"
                            },
                            "oe-fragments": {
                                "$anchor": "oe-fragments",
                                "type": "array",
                                "description": "List of BitBake configuration fragments to enable",
                                "items": {
                                    "type": "string"
                                }
                            },
                            "oe-fragments-one-of": {
                                "type": "object",
                                "description": "Mutually exclusive bitbake configuration fragment",
                                "patternProperties": {
                                    ".*": {
                                        "type": "object",
                                        "required": [
                                            "description",
                                            "options"
                                        ],
                                        "properties": {
                                            "description": {
                                                "type": "string",
                                                "description": "Human-readable description of the fragment category"
                                            },
                                            "options": {
                                                "$ref": "#oe-fragments"
                                            }
                                        },
                                        "additionalProperties": false
                                    }
                                },
                                "additionalProperties": false
                            },
                            "configurations": {
                                "$ref": "#configurations"
                            },
                            "bb-env-passthrough-additions": {
                                "type": "array",
                                "description": "List of environment variables to include in BB_ENV_PASSTHROUGH_ADDITIONS",
                                "items": {
                                    "type": "string"
                                }
                            }
                        },
                        "additionalProperties": false
                    }
                }
            },
            "additionalProperties": false
        },
        "version": {
            "description": "The version of this document; currently '1.0'",
            "enum": [
                "1.0"
            ]
        }
    },
    "additionalProperties": false
}

=== voltumna-linux/meta-voltumna/default-registry/configurations/poky-master.conf.json
{
    "description": "Poky - The Yocto Project testing distribution configurations and hardware test platforms",
    "sources": {
        "bitbake": {
            "git-remote": {
                "remotes": {
                    "origin": {
                        "uri": "git://git.openembedded.org/bitbake;protocol=https"
                    }
                },
                "branch": "master",
                "rev": "master"
            },
            "path": "bitbake"
        },
        "openembedded-core": {
            "git-remote": {
                "remotes": {
                    "origin": {
                        "uri": "git://git.openembedded.org/openembedded-core;protocol=https"
                    }
                },
                "branch": "master",
                "rev": "master"
            },
            "path": "openembedded-core"
        },
        "meta-yocto": {
            "git-remote": {
                "remotes": {
                    "origin": {
                        "uri": "git://git.yoctoproject.org/meta-yocto;protocol=https"
                    }
                },
                "branch": "master",
                "rev": "master"
            },
            "path": "meta-yocto"
        },
        "yocto-docs": {
            "git-remote": {
                "remotes": {
                    "origin": {
                        "uri": "git://git.yoctoproject.org/yocto-docs;protocol=https"
                    }
                },
                "branch": "master",
                "rev": "master"
            },
            "path": "yocto-docs"
        }
    },
    "bitbake-setup": {
        "configurations": [
        {
            "bb-layers": ["openembedded-core/meta","meta-yocto/meta-yocto-bsp","meta-yocto/meta-poky"],
            "oe-fragments-one-of": {
                "machine": {
                    "description": "Target machines",
                    "options" : ["machine/qemux86-64", "machine/qemuarm64", "machine/qemuriscv64", "machine/genericarm64", "machine/genericx86-64"]
                },
                "distro": {
                    "description": "Distribution configuration variants",
                    "options" : ["distro/poky", "distro/poky-altcfg", "distro/poky-tiny"]
                }
            },
            "configurations": [
            {
                "name": "poky",
                "description": "Poky - The Yocto Project testing distribution"
            },
            {
                "name": "poky-with-sstate",
                "description": "Poky - The Yocto Project testing distribution with internet sstate acceleration. Use with caution as it requires a completely robust local network with sufficient bandwidth.",
                "oe-fragments": ["core/yocto/sstate-mirror-cdn"]
            }
            ]
        }
        ]
    },
    "version": "1.0"
}

=== voltumna-linux/meta-voltumna/default-registry/configurations/oe-nodistro.conf.json
{
    "description": "OpenEmbedded - 'nodistro' basic configuration",
    "sources": {
        "bitbake": {
            "git-remote": {
                "remotes": {
                    "origin": {
                        "uri": "git://git.openembedded.org/bitbake;protocol=https"
                    }
                },
                "branch": "master",
                "rev": "master"
            },
            "path": "bitbake"
        },
        "openembedded-core": {
            "git-remote": {
                "remotes": {
                    "origin": {
                        "uri": "git://git.openembedded.org/openembedded-core;protocol=https"
                    }
                },
                "branch": "master",
                "rev": "master"
            },
            "path": "openembedded-core"
        },
        "yocto-docs": {
            "git-remote": {
                "remotes": {
                    "origin": {
                        "uri": "git://git.yoctoproject.org/yocto-docs;protocol=https"
                    }
                },
                "branch": "master",
                "rev": "master"
            },
            "path": "yocto-docs"
        }
    },
    "bitbake-setup": {
        "configurations": [
        {
            "name": "nodistro",
            "description": "OpenEmbedded 'nodistro'",
            "bb-layers": ["openembedded-core/meta"],
            "oe-fragments-one-of": {
                "machine": {
                    "description": "Target machines",
                    "options" : ["machine/qemux86-64", "machine/qemuarm64", "machine/qemuriscv64"]
                }
            }
        }
        ]
    },
    "version": "1.0"
}
